apiVersion: v2
name: crossplane-resource
description: Crossplane provider, XRD, and Composition for Object (ConfigMap + nginx Deployment)
type: application
version: 0.1.0
appVersion: "1.0.0"
preferredNamespace: crossplane-resource
