{{- if .Values.example.enabled }}
apiVersion: demo.crossplane.io/v1alpha1
kind: Object
metadata:
  name: {{ .Values.example.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  # Passed into ConfigMap data.static and shown by nginx
  content: |
{{ .Values.example.content | indent 4 }}
{{- end }}
